### ISSUE TITLE
DRT extension only allows 1 thread for the qsim module?

### ISSUE THREAD

**Issue by Aitanm** [matsim-org/matsim-maas#4]
I'm getting an exception when I'm trying to increase the number of threads for qsim in my simulations. My question is that if DRT only allows 1 thread or there is any config parameter that enables to increase number of threads for qsim?
(increasing number of threads for the other modules is working).

exception: 

```
Exception in thread "main" java.lang.RuntimeException: Only a single-threaded QSim allowed
	at org.matsim.contrib.drt.run.DrtConfigConsistencyChecker.checkConsistency(DrtConfigConsistencyChecker.java:54)
	at org.matsim.core.config.Config.checkConsistency(Config.java:228)
	at org.matsim.contrib.drt.run.DrtControlerCreator.createControlerWithSingleModeDrt(DrtControlerCreator.java:92)
	at org.matsim.contrib.drt.run.DrtControlerCreator.createControlerWithSingleModeDrt(DrtControlerCreator.java:72)
	at org.matsim.maas.drt.RunDRT.run(RunDRT.java:59)
	at org.matsim.maas.drt.RunDRT.main(RunDRT.java:74)
```

**Comment by michalmac** [comment]
We want to add the ability to run DRT/taxi etc. with the parallel QSim soon.

Please note that the DRT optimisation is already multi-threaded, but consumes much more CPU time than the single-threaded QSim, so I would not expect huge gains (except for scenarios with a very small DRT/taxi shares).

**Comment by michalmac** [comment]
Answering the other question: There are 3 separate parameters in the config:
- `QSimConfigGroup.numberOfThreads` - this needs to be 1 currently
- `GlobalConfigGroup.numberOfThreads` - this is used in many other places (including replanning) and can be set to higher values than 1
- `DrtConfigGroup.numberOfThreads` - this is used solely by DRT; the suggested value is 4 (values 5+ will not give much more of a speedup, at least currently)

**Comment by Aitanm** [comment]
Thanks a lot you for the prompt and detailed response.
